services:
  db:
    image: postgres:17.0-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - full-todo:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

volumes:
  full-todo:
